-- MySQL Script generated by MySQL Workbench
-- Mon Jul 15 22:49:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cine_pruebas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine_pruebas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine_pruebas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cine_pruebas` ;

-- -----------------------------------------------------
-- Table `cine_pruebas`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`salas` (
  `sala_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sala_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`asientos` (
  `asientos_id` INT NOT NULL AUTO_INCREMENT,
  `numero_asiento` INT NOT NULL,
  `seccion` VARCHAR(45) NOT NULL,
  `sala_id` INT NOT NULL,
  `estado_asiento` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`asientos_id`),
  INDEX `salas_id_idx` (`sala_id` ASC) VISIBLE,
  CONSTRAINT `salas_asientos_id`
    FOREIGN KEY (`sala_id`)
    REFERENCES `cine_pruebas`.`salas` (`sala_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`peliculas` (
  `pelicula_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `duracion` INT NOT NULL,
  `rating` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`pelicula_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`horarios` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `pelicula_id` INT NOT NULL,
  `sala_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`horario_id`),
  INDEX `fk_horarios_peliculas` (`pelicula_id` ASC) VISIBLE,
  INDEX `fk_horarios_salas` (`sala_id` ASC) VISIBLE,
  CONSTRAINT `fk_horarios_peliculas`
    FOREIGN KEY (`pelicula_id`)
    REFERENCES `cine_pruebas`.`peliculas` (`pelicula_id`),
  CONSTRAINT `fk_horarios_salas`
    FOREIGN KEY (`sala_id`)
    REFERENCES `cine_pruebas`.`salas` (`sala_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`ventas` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `pelicula_id` INT NOT NULL,
  `horario_id` INT NOT NULL,
  `fecha_venta` DATE NOT NULL,
  PRIMARY KEY (`venta_id`),
  INDEX `fk_ventas_clientes` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_ventas_peliculas` (`pelicula_id` ASC) VISIBLE,
  INDEX `fk_ventas_horarios` (`horario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_clientes`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cine_pruebas`.`clientes` (`cliente_id`),
  CONSTRAINT `fk_ventas_horarios`
    FOREIGN KEY (`horario_id`)
    REFERENCES `cine_pruebas`.`horarios` (`horario_id`),
  CONSTRAINT `fk_ventas_peliculas`
    FOREIGN KEY (`pelicula_id`)
    REFERENCES `cine_pruebas`.`peliculas` (`pelicula_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
