-- MySQL Script generated by MySQL Workbench
-- Mon Jul 15 18:21:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cine_pruebas_2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cine_pruebas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine_pruebas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine_pruebas` DEFAULT CHARACTER SET utf8mb3 ;
USE `cine_pruebas` ;

-- -----------------------------------------------------
-- Table `cine_pruebas`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`asientos` (
  `asientos_id` INT NOT NULL AUTO_INCREMENT,
  `numero_asiento` INT NULL DEFAULT NULL,
  `seccion_asiento` VARCHAR(45) NULL DEFAULT NULL,
  `estado_asiento` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`asientos_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`salas` (
  `sala_id` INT NOT NULL AUTO_INCREMENT,
  `sitio` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`sala_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`ventas` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `numero_asiento` INT NULL DEFAULT NULL,
  `pelicula_id` INT NULL DEFAULT NULL,
  `sala_id` INT NULL,
  `fecha_venta` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`venta_id`),
  INDEX `fk_ventas_salas1_idx` (`sala_id` ASC) VISIBLE,
  INDEX `fk_ventas_asientos1_idx` (`numero_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_salas1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `cine_pruebas`.`salas` (`sala_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_asientos1`
    FOREIGN KEY (`numero_asiento`)
    REFERENCES `cine_pruebas`.`asientos` (`asientos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `fk_clientes_ventas`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cine_pruebas`.`ventas` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cine_pruebas`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_pruebas`.`peliculas` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` VARCHAR(45) NULL DEFAULT NULL,
  `ratin` INT NULL DEFAULT '0',
  PRIMARY KEY (`movie_id`),
  CONSTRAINT `fk_peliculas_ventas1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cine_pruebas`.`ventas` (`pelicula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
